global:
model_list:
  - model_name: gemma3
        params:
          model: gemma3
          api_base: http://ollama-service.ollama.svc.cluster.local:11434/v1
          drop_params: false
          api_key: "no_token"
          max_input_tokens: 25000
          vision: true
     
  - model_name: devstral
    params:
      model: devstral:latest
      api_base: http://ollama-service.ollama.svc.cluster.local:11434/v1
      drop_params: false
      api_key: "no_token"
      max_input_tokens: 25000

keys:
  - name: "user"
    token: "token"
    models:
      - "qwen3"
      - "devstral"
    max_concurrent_requests: 10
    max_requests_per_minute: 6