global:
  influxdb:
    url: http://localhost:8086
    token: your_token
    org: your_org
    bucket: your_bucket
model_list:
  - model_name: qwen3
        params:
          model: qwen3:14b
          api_base: http://ollama-service.ollama.svc.cluster.local:11434/v1
          drop_params: true
          api_key: "no_token"
          max_input_tokens: 25000
          co2:
            watt: 500
            gram_per_kwh: 50
     
  - model_name: devstral
    params:
      model: devstral:latest
      api_base: http://ollama-service.ollama.svc.cluster.local:11434/v1
      drop_params: true
      api_key: "no_token"
      max_input_tokens: 25000
      co2:
        watt: 500
        gram_per_kwh: 50

keys:
  - name: "user"
    token: "token"
    models:
      - "qwen3"
      - "devstral"
    max_concurrent_requests: 10
    max_requests_per_minute: 6