metrics_auth:
  username: admin
  password: your-secure-password
model_list:
  - model_name: gemma3
        params:
          model: gemma3
          api_base: http://ollama-service.ollama.svc.cluster.local:11434/v1
          drop_params: false
          api_key: "no_token"
          max_input_tokens: 25000
          cost_per_input_token: 0.25
          cost_per_output_token: 0.80
          vision: true
     
  - model_name: devstral
    params:
      model: devstral:latest
      api_base: http://ollama-service.ollama.svc.cluster.local:11434/v1
      drop_params: false
      api_key: "no_token"
      max_input_tokens: 25000
      cost_per_token: 0.15
keys:
  - name: "user"
    token: "token"
    models:
      - "qwen3"
      - "devstral"
    rpm_limit: 5
