name: opencode
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
jobs:
  opencode:
    if: |
      contains(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, '/opencode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git identity
        run: |
          git config --global user.email "opencode-bot@users.noreply.github.com"
          git config --global user.name "opencode-bot"

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          OPEN_CODE_API_KEY: ${{ secrets.OPEN_CODE_API_KEY }}
          OPEN_CODE_API_URL: ${{ secrets.OPEN_CODE_API_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: erasme-ai-proxy/qwen3.6
          use_github_token: true
